### PR TITLE
feature/discord

### LINKED ISSUE #91: [vscode] Add new chat provider: Discord
There are lot of open source project using Discord as a tool for communication (React, Vue.js, Nuxt.js).

With the integration in the VS Code directly, it can be really easy to chat with the community and ask question without leaving the code editor.

### PR DESCRIPTION
**Pull request by arjun27**
Closes #91

### CODE REVIEW

**Comment by arjun27** [comment]
Pre-release build 1 is available to download at [this link](https://drive.google.com/open?id=1FcdHVPDophzmpyhJSljkyknCo138cGxi).

## Setup
1. Download the `chat-0.6.0-pre-1.vsix` file from the link given above
2. Open VS Code, and select the **Extensions: Install from VSIX** command from the command palette
3. Reload VS Code after the installation

## Authentication
To use Discord inside VS Code, you need to have your Discord token. To obtain your token, follow the steps [given here](https://discordhelp.net/discord-token).

This is an unofficial token setup, one that is used by other Discord clients ([Discline](https://github.com/MitchWeaver/Discline), [terminal-discord](https://github.com/xynxynxyn/terminal-discord)), and the recommended approach by a Discord team member, as [given here](https://github.com/discordapp/discord-api-docs/issues/69#issuecomment-223886862):

> Instead, log in on the discord client, pop open the web inspector, (ctrl/cmd shift I), and type localStorage.token in the console to get your auth token.

The goal is to move to [Discord RPC](https://discordapp.com/developers/docs/topics/rpc#proxied-api-requests) in the near-term, which supports proxied API/websocket requests with OAuth. Discord RPC is in private beta at the moment. If you have any suggestions to improve this flow, please share.

Once you have the token, run the following commands from the VS Code command palette

1. Run **Slack: Configure Access Token**, select "Discord", and paste your token in the input box. This will save the token to your system keychain.
2. Next, you will be prompted to choose your primary Discord guild (similar to Slack workspaces). If you don't want to select now, you can run the **Slack: Change Workspace** command to select your guild.

## Known issues (fixes coming in future builds)

1. The extension is still branded as a "Slack" client, which can get confusing for Discord users. This will be fixed in upcoming releases.
2. For large communities (like Reactiflux, with 2.5k members) fetching member data can be very slow. Currently the extension only fetches data up to 500 members.
3. Unreads are counted only updated after the extension has been activated, which means messages that were received before you open VS Code are not counted into the unread count.
4. Message reactions, edits, file attachments, link unfurls are not supported currently. Live share (and other) links are not rendered as clickable.
5. Users that are not a part of your selected guild, but with open direct messages are not fetched. These will appear as bare ids.
6. Live share invitations can only be sent to users that are a part of your selected guild.
7. For large communities, a loader is required while member/channel data is fetched. There is no loader currently
8. The current guild name is not displayed anywhere, which can be a cause of confusion (feedback welcome!)
9. For large communities, performance is sluggish at times while updating data in the tree view

**Comment by mittalyashu** [comment]
I have created this chat icon.

image

Here's the svg source:

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 437.212 437.212"><path d="M404.812 41.206h-300c-18 0-32.4 14.8-32.4 32.4v186.4c0 18 14.8 32.4 32.4 32.4h206.8l46.8 47.2c2 2 4.4 3.2 7.2 3.2 5.6 0 10.4-4.4 10.4-10.4v-40h28.8c18 0 32.4-14.8 32.4-32.4v-186.4c0-18-14.8-32.4-32.4-32.4zm-254 160.4c-16.4 0-30-13.6-30-30s13.6-30 30-30 30 13.6 30 30-13.2 30-30 30zm105.2 0c-16.4 0-30-13.6-30-30s13.6-30 30-30 30 13.6 30 30-13.6 30-30 30zm104.8 0c-16.4 0-30-13.6-30-30s13.6-30 30-30 30 13.6 30 30-13.6 30-30 30z"/><path d="M54.012 260.806v-63.6h-32.8c-11.6 0-21.2 9.6-21.2 21.2v122.4c-.4 12.4 9.2 22 21.2 22h18.8v26.4c0 3.6 3.2 6.8 6.8 6.8 2 0 3.6-.8 4.8-2l30.8-30.8h136c11.6 0 21.2-9.6 21.2-21.2v-30.4h-134.8c-28 0-50.8-22.8-50.8-50.8z"/></svg>
```

**Comment by arjun27** [comment]
Build 3 is now available for testing. Link and instructions update in the comment above

**Comment by mittalyashu** [comment]
There is this weird heading in `readme.md` file.

image

**Comment by mittalyashu** [comment]
Image in [this section](https://github.com/karigari/vscode-chat/blob/feature/discord/README.md#vs-live-share) is no of high res.

**Pull request merged**
